### ISSUE TITLE
iPhone X Formatting/Bug issues

### ISSUE THREAD

**Issue by BetterYouCode** [BetterYouCode/BetterYou#1]
Shouldn't have a back arrow as its the homepage of the map tab. Teams icon in the top right is too high. When the 3x3 icon is pressed in the right corner, the cards should mirror it changing to a smaller 3x3 to view more at once. Not flip and turn into scroll.
![img_3445](https://user-images.githubusercontent.com/39304144/40489198-352bb234-5f2e-11e8-87fd-42988c892ee9.PNG)
Navigation is hard to press, too close to top.
![img_3444](https://user-images.githubusercontent.com/39304144/40489199-354b4298-5f2e-11e8-843d-0d6853f42891.PNG)
Navigation is hard to press, too close to top.
![img_3443](https://user-images.githubusercontent.com/39304144/40489200-356e7128-5f2e-11e8-93d9-c06792866ef1.PNG)
When the 3x3 icon is pressed in the right corner, the cards should mirror it changing to a smaller 3x3 to view more at once. 
![img_3442](https://user-images.githubusercontent.com/39304144/40489201-35d8b4b6-5f2e-11e8-803a-1f37130c10b4.PNG)
Navigation is hard to press, too close to top.
![img_3441](https://user-images.githubusercontent.com/39304144/40489202-35f7b8b6-5f2e-11e8-8252-d675467c2340.PNG)
Navigation is hard to press, too close to top.
![img_3440](https://user-images.githubusercontent.com/39304144/40489203-361bd03e-5f2e-11e8-91cf-dced8c9344fe.PNG)
Navigation is hard to press, too close to top. When a blue button is pressed an integer counts up on it. Press and hold to decrease. 
![img_3439](https://user-images.githubusercontent.com/39304144/40489204-36736394-5f2e-11e8-9b48-27705091350a.PNG)
Can't see "What's new BetterYou?" button, The inspiration icon is cut off, BoostPoint Market should be switched to Market.
![img_3438](https://user-images.githubusercontent.com/39304144/40489205-369d50fa-5f2e-11e8-80aa-2e34400bd8f0.PNG)
The continue button is barley visible and hard to press.
![img_3437](https://user-images.githubusercontent.com/39304144/40489207-36bba8b6-5f2e-11e8-8b78-03532291adb4.PNG)

**Comment by kishanj918** [comment]
fixed.

**Comment by BetterYouCode** [comment]
Updates look great!
