### ISSUE TITLE
Small Text Changes

### ISSUE THREAD

**Issue by BetterYouCode** [BetterYouCode/BetterYou#2]
"What's new BetterYou?" - bottom button
Feed will now be "Articles"
Change "Connecting Communities to Holistic Health" to "Empower Growth"
![img_3648](https://user-images.githubusercontent.com/39304144/40791127-52dbe1a8-64bc-11e8-9e6f-c558d715cdd0.PNG)
feed will now be "Articles"
<img width="362" alt="screen shot 2018-05-29 at 11 38 39 am" src="https://user-images.githubusercontent.com/39304144/40791497-46357076-64bd-11e8-9699-eb1c5d848c45.png">

**Comment by kishanj918** [comment]
fixed it please check it out

**Comment by BetterYouCode** [comment]
Looks great.
