### ISSUE TITLE
Home Screen Pagination

### ISSUE THREAD

**Issue by BetterYouCode** [BetterYouCode/BetterYou#4]
Middle pagination icons are too large. They are being cutoff on the top and bottom. We can just shrink those down.
![img_3648](https://user-images.githubusercontent.com/39304144/40793365-d7e891c0-64c1-11e8-9b16-dd8e6b430cc8.PNG)
![img_3651](https://user-images.githubusercontent.com/39304144/40793368-da7cf6ec-64c1-11e8-8cff-0e8c320d383a.PNG)
![img_3652](https://user-images.githubusercontent.com/39304144/40793370-dcd75e50-64c1-11e8-97d0-6dc76d197e33.PNG)

**Comment by kishanj918** [comment]
fixed please check it out

**Comment by BetterYouCode** [comment]
Looks good, I'm not sure why its in a scroll view. Closing for now.
