### ISSUE TITLE
No search for profiles

### ISSUE THREAD

**Issue by BetterYouCode** [BetterYouCode/BetterYou#6]
For the current flow of the app there is no way for users to search other peoples profiles. This does not need to be a fancy screen, we can mock how facebook does it. Just a search bar. 

Suggested flow:
Change the "Visit Profile" in the home screen pagination to "Search Profiles"

Click "Search Profiles" ---> This screen
![img_3881](https://user-images.githubusercontent.com/39304144/41168214-e5a063b6-6b0a-11e8-8a86-8f54b4a993b1.PNG)

**Comment by kishanj918** [comment]
added these screen in 11th June, 2018's build.
following is snapshot of designed screen.
we complete your requirement as per our theme, if you want same page as you provide, we will complete it soon.

![simulator screen shot - iphone 6 - 2018-06-11 at 21 02 41](https://user-images.githubusercontent.com/3994657/41241659-245f2c7e-6dbb-11e8-853d-0c248dbe8064.png)

sorry we forgot to remove tabbar, it will remove in next build. (i seen this now.)

**Comment by BetterYouCode** [comment]
Okay perfect, format looks great!

**Comment by BetterYouCode** [comment]
Also when tab bar is removed, edit for iPhone X formatting as well. Otherwise looks great!
