### ISSUE TITLE
Articles, Fitness, Nutrition

### ISSUE THREAD

**Issue by BetterYouCode** [BetterYouCode/BetterYou#7]
All of the feeds of these are the same color, blue and flat.

They are suppose to be:
Articles: white and card style like teams
Fitness: blue and card style like teams
Nutrition: green and card style like teams

<img width="207" alt="image" src="https://user-images.githubusercontent.com/39304144/41168396-745f380c-6b0b-11e8-8208-757c7fa67338.png">
<img width="112" alt="image" src="https://user-images.githubusercontent.com/39304144/41168454-a2cb6ca6-6b0b-11e8-8b9f-3625b3ac032f.png">
<img width="231" alt="image" src="https://user-images.githubusercontent.com/39304144/41168415-7f284328-6b0b-11e8-8193-e298c6120557.png">

Card style. This is what we would like all of the fields to look like, just with their specific color. Shadow can be black on all of them.
![img_5d4cd4053fe9-1](https://user-images.githubusercontent.com/39304144/41168514-ce463668-6b0b-11e8-9263-bcda8db69099.jpeg)

**Comment by kishanj918** [comment]
issue is fixed in 11th june, 2018 build.

**Comment by BetterYouCode** [comment]
Looks great!
